# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'IvVk' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  pod 'Alamofire', '~> 4.8.2'
#pod 'AlamofireObjectMapper', '~> 5.2'
  pod 'SwiftKeychainWrapper'
  pod 'RealmSwift'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  # Pods for IvVk

end
